packages:
  - 'apps/*'
  - 'packages/*'

minimumReleaseAge: 1440
blockExoticSubdeps: true
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
allowBuilds:
  '@prisma/engines': true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  ssh2: true
